modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ourmod"
version="2.0.0"
displayName="OurMod"
displayURL="https://example.com"
logoFile=""
credits="Big Ev"
authors="Big Ev"
description="""
A simple test mod.
"""
